# @name CreateOrder
POST {{ orderServiceHost }}/orders
Content-Type: application/json

{
  "firstName": "Firstname",
  "lastName": "Lastname",
  "email": "me@company.com"
}

> {%
    client.global.set("order_id", response.body["id"]);
%}

### 

# @name CreateOrderWithoutAdditionalSpace
POST {{ orderServiceHost }}/orders/no-additional-space
Content-Type: application/json

{
  "firstName": "No",
  "lastName": "Space",
  "email": "no@space.com"
}

> {%
    client.global.set("order_id", response.body["id"]);
%}

### 

# @name FindOrder
GET {{ orderServiceHost }}/orders/{{ order_id }}
Accept: application/json

